### ISSUE TITLE
Unavailable Animal: Notice: Undefined offset: 0 

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#133]
We're getting an error:

https://bloomington.in.gov/animal-shelter/animals/58840

Also:

"This animal is no longer available. Please choose an option to see other animals that available for adoption."

should read:
"This animal is no longer available. Please choose an option to see other animals that are available for adoption."

**Comment by inghamn** [comment]
Sorry, I forgot to deploy the updated animal shelter module to production.  I've deployed it now.

**Comment by rbdietz** [comment]
Still missing words.  Make sure the grammar is correct.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
